name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-06"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTYyNmQwMDctODE5OC00YzJjLTgzNTgtOTNiOTIwZWFlNjdlIiwidGVuYW50X2lkIjoiODc3OWIzZjkyODU0MTgwODRkZTE1ODA4OWNiZmNhMmExMWRhNzhmNGJhYWM3OTM1MWNmNjZmYmRiN2QzZDFhYSIsImludGVybmFsX3NlY3JldCI6ImYxZjQ1ZjUxLTUzODctNDY2OC1hZTYwLWIwZTQ0MmQ2Mzc1NCJ9.lkwiwLvxMyrD-R6LY-HhHTMf-isC6migB5bvWt6lDK4"
JWT_SECRET= "KrishSecret"